using System;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace ConfigManager.Generator;

internal record struct AttributeCode(string Name, string Namespace, string GenAttribute, PropertyCode[] Properties,
    AttributeTargets[] Targets, string AttributeAccessModifier = "internal",
    string ConstructorAccessModifier = "internal", bool AllowMultiple = false, bool Inherited = false,
    string? Other)
{
    internal string GetCode()
    {
        string usages = "[global::System.AttributeUsage({targets, })]";
        string constructor = "public ";
        string properties = "";

        string

        string code =
            $$"""
            // <auto-generated>
            #nullable enable
            namespace {{Namespace}}
            {
                {{GenAttribute}}
                {{usages}}
                {{AttributeAccessModifier}} sealed class {{Name}} : global::System.Attribute
                {
                    {{properties}}
                    {{constructor}}
                }
            }
            """;

        return code;
    }
}
