//HintName: Generated_IConfig.cs
// <auto-generated>
#nullable enable
namespace ConfigManager.Attributes
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute(tool: "ConfigPropertyChangeGenerator", version: "1.0.0.0")]
    public interface IConfig
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute(tool: "ConfigPropertyChangeGenerator", version: "1.0.0.0")]
        public void Save();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute(tool: "ConfigPropertyChangeGenerator", version: "1.0.0.0")]
        public static IConfig Load();
    }
}