//HintName: Generated_ConfigIgnoreAttribute.cs
// <auto-generated>
#nullable enable
namespace ConfigManager.Attributes
{
    [global::System.AttributeUsageAttribute(global::System.AttributeTargets.Field, AllowMultiple = false, Inherited = false)]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute(tool: "ConfigPropertyChangeGenerator", version: "1.0.0.0")]
    public class ConfigIgnoreAttribute : global::System.Attribute
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute(tool: "ConfigPropertyChangeGenerator", version: "1.0.0.0")]
        public ConfigIgnoreAttribute()
        {
        }
    }
}