//HintName: Generated_ConfigAttribute.cs
// <auto-generated>
#nullable enable
namespace ConfigManager.Attributes
{
    [global::System.AttributeUsageAttribute(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute(tool: "ConfigPropertyChangeGenerator", version: "1.0.0.0")]
    public class ConfigAttribute : global::System.Attribute
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute(tool: "ConfigPropertyChangeGenerator", version: "1.0.0.0")]
        public ConfigAttribute()
        {
        }
    }
}